


GET http://127.0.0.1:8000/planetas HTTP/1.1
###
GET http://127.0.0.1:8000/planetas/1 HTTP/1.1

###

POST http://127.0.0.1:8000/planetas HTTP/1.1
Content-Type: "application/json"

{
    "nome": "Netuno",
    "galaxia_id": "7"

}

###

DELETE http://127.0.0.1:8000/planetas/1 HTTP/1.1

###

PUT http://127.0.0.1:8000/planetas/2 HTTP/1.1
Content-Type: "application/json"

{
    "nome": "Saturno",
    "galaxia_id": "4"

}
